#!/usr/bin/env bash
set -euo pipefail

datadir=$1

while true; do
    {
        rsync -rt --info=NAME \
            --timeout=10 \
            "$datadir"/blobs \
            'onlytrains@[fe80::d250:99ff:fe1c:2505%eth0]:./data/'
        rsync -rt --info=NAME \
            --timeout=10 \
            "$datadir"/db.sqlite3 \
            'onlytrains@[fe80::d250:99ff:fe1c:2505%eth0]:./data/'
            find "$datadir/blobs" -type f -mtime +30 -delete
        } || true
    inotifywait --event=modify --timeout 3600 "$datadir"/db.sqlite3
done

