[package]
name = "trainbot-core"
version = "0.1.0"
edition = "2021"

[dependencies]
pmatch = { path = "../cv/pmatch" }
avg = { path = "../cv/avg" }
ransac = { path = "../cv/ransac" }
vid = { path = "../vid" }
image = { workspace = true, features = ["jpeg", "png"] }
thiserror = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "fmt",
  "json",
] }
metrics = "0.24"
metrics-exporter-prometheus = { version = "0.16", default-features = false }
gif = "0.13"
color_quant = "1.1"
crossbeam-channel = "0.5"
duct = { workspace = true }
mkv-element = "0.4.0"
bytes = "1.12.0"
clap = { workspace = true }
scopeguard = "1.2.0"

[dev-dependencies]
image = { workspace = true, features = ["jpeg", "png"] }
