name: cached-docker-build
description: Run a cached Docker build from within make
inputs:
  chdir:
    description: Directory to change into before the build
    required: true
    default: '.'
  target:
    description: Make target to execute
    required: true
runs:
  using: composite
  steps:
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v3
  - name: Set up cache
    uses: actions/cache@v4
    with:
      path: /tmp/buildx-cache
      key: buildx-${{ runner.os }}-${{github.job}}-${{ github.sha }}
      restore-keys: buildx-${{ runner.os }}-${{github.job}}-
  - name: Build and push
    shell: bash
    run: |
      cd ${{inputs.chdir}}
      make \
        DOCKER_CLI_FLAGS="--cache-from type=local,src=/tmp/buildx-cache --cache-to type=local,dest=/tmp/buildx-cache-new,mode=max" \
        ${{inputs.target}}
  - name: Move cache, see https://github.com/docker/build-push-action/issues/252
    shell: bash
    run: |
      rm -rf /tmp/buildx-cache
      mv /tmp/buildx-cache-new /tmp/buildx-cache
  - name: List cache
    shell: bash
    run: |
      ls -lh /tmp/buildx-cache
      du -sh /tmp/buildx-cache
